### ISSUE TITLE
Based UI

### ISSUE THREAD

**Issue by andriejs** [face-hh/feddit#1]
![image](https://github.com/face-hh/feddit/assets/72381315/72003cd2-28da-415a-bba1-b1b8e1c3ecb2)

Btw, It seems as you didn't use react which could've made your job 99% easier.

**Comment by face-hh** [comment]
that's probably because of your screen size, i didn't include any @media keys, so it's gonna be quite buggy on displays that are not 16:9 or with zoom enabled

**Comment by andriejs** [comment]
@face-hh 
Hmm?
![image](https://github.com/face-hh/feddit/assets/72381315/c94f635f-39ae-43be-aef3-cd2a052506ef)

**Comment by face-hh** [comment]
as i said, "it's gonna be quite buggy [...] with zoom enabled"

try decreasing the zoom

**Comment by andriejs** [comment]
There. Also it never loads. 
![image](https://github.com/face-hh/feddit/assets/72381315/8dee062a-848a-485e-923b-61109b4dbfd3)

**Comment by andriejs** [comment]
> probably because the subreddit doesn't exist

subfeddit*

i made a post, on asubfeddit that EXISTS. same issue.

**Comment by andriejs** [comment]
![image](https://github.com/face-hh/feddit/assets/72381315/82986ffb-61a1-47bf-9124-be90e7579b64)

**Comment by face-hh** [comment]
got it, i'll try fixing it right now

**Comment by face-hh** [comment]
fixed
