### ISSUE TITLE
feddit.space doesn't work

### ISSUE THREAD

**Issue by rntdev1** [face-hh/feddit#7]
oh no I wanted to discover some fancy XSS and steal all tokens before going to bed

**Comment by face-hh** [comment]
Sorry but the website is no longer being hosted 🙂

**Comment by rntdev1** [comment]
sad

**Comment by giftedl** [comment]
Absolutely horrendous. His channel is dead. His career is dead. Hes a fake programmer. So pathetic @face-hh. /j
