### ISSUE TITLE
404 on https://feddit.space/login

### ISSUE THREAD

**Issue by Stoppedwumm** [face-hh/feddit#8]
When I tried the website (<https://feddit.space/login>), nginx threw a 404 at me, same as <https://feddit.space>

**Comment by Stoppedwumm** [comment]
[![Typing SVG](https://readme-typing-svg.demolab.com/?lines=Fix-it)](https://git.io/typing-svg)

**Comment by SyntaxError52** [comment]
Me 2

**Comment by iPigTW** [comment]
lmfao

**Comment by ghost** [comment]
It hasn't been hosted for like half a year lol

**Comment by tigercoding56** [comment]
just self host it

**Comment by vixenowo** [comment]
chaos ended
